In [ ]:
# Treinando e avaliando modelo preditivo usando VALIDAÇÃO CRUZADA

# Importa bibliotecas necessárias 
import numpy as np
from sklearn import  model_selection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_digits
import pandas as pd

# Carregando a base digits
X, y = load_digits(return_X_y=True)
print(X.shape)
print(y.shape)

# declarando o modelo
clf = KNeighborsClassifier(n_neighbors=3,weights='distance',algorithm='ball_tree')

# Usando a validação cruzada com 10 folds neste exemplo.
folds=10
result = model_selection.cross_val_score(clf, X, y, cv=folds)

# mostrando a acurácia média e desvio padrão.
print("\nCross Validation Results %d folds:" % folds)
print("Mean Accuracy: %.5f" % result.mean())
print("Mean Std: %.5f" % result.std())

# matriz de confusão da validação cruzada
predicted = model_selection.cross_val_predict(clf, X, y, cv=folds)
cm=confusion_matrix(y, predicted)

print("Confusion Matrix:")
print(cm)


(1797, 64)
(1797,)

Cross Validation Results 10 folds:
Mean Accuracy: 0.97718
Mean Std: 0.01619
Confusion Matrix:
[[178   0   0   0   0   0   0   0   0   0]
 [  0 180   0   0   0   1   1   0   0   0]
 [  0   4 171   1   0   0   0   0   1   0]
 [  0   0   0 175   0   2   0   2   3   1]
 [  0   1   0   0 178   0   1   0   0   1]
 [  0   0   0   0   0 178   1   0   0   3]
 [  0   1   0   0   0   1 179   0   0   0]
 [  0   0   0   0   0   0   0 178   0   1]
 [  0   6   0   0   0   0   0   0 168   0]
 [  0   1   0   4   1   1   0   0   2 171]]
