In [ ]:
# Treinando e avaliando modelo preditivo usando HOLDOUT

# Importa bibliotecas necessárias 
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

# Carregando a base de dados Digits
X, y = load_digits(return_X_y=True)
print(X.shape)
print(y.shape)

# Holdout -> dividindo a base em treinamento e teste. Neste exemplo, treinamento (70%) e teste (30%), estratificada
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3, random_state=42, stratify=y)

# Declarando o classificador
clfa = KNeighborsClassifier(n_neighbors=3)

# Treinando o classificador
clfa = clfa.fit(X_train, y_train)

# Testando na base de testes
predicted=clfa.predict(X_test)

# Calculando a acurácia na base de teste
score=clfa.score(X_test, y_test)

# Calculando a matriz de confusão
matrix = confusion_matrix(y_test, predicted)

# Apresentando os resultados (acurácia neste exemplo)
print("Accuracy = %.5f" % (score*100))

# Apresentando a matriz de confusão
print("Confusion Matrix:")
print(matrix)

# salvando o modelo
from joblib import dump, load
with open("clfa.mod", 'wb') as fo:  
    dump(clfa, fo)



(1797, 64)
(1797,)
Accuracy = 98.70370
Confusion Matrix:
[[54  0  0  0  0  0  0  0  0  0]
 [ 0 55  0  0  0  0  0  0  0  0]
 [ 0  0 53  0  0  0  0  0  0  0]
 [ 0  0  0 55  0  0  0  0  0  0]
 [ 0  0  0  0 54  0  0  0  0  0]
 [ 0  0  0  0  0 54  0  0  0  1]
 [ 0  0  0  0  0  0 54  0  0  0]
 [ 0  0  0  0  0  0  0 54  0  0]
 [ 0  3  0  0  0  0  1  0 48  0]
 [ 0  0  0  0  1  0  0  0  1 52]]
